---
title: "InSitu vs Analysis Comparision"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
----------------------------------------------------------------------

```{r, include=FALSE}
source("T:/Benthic/Data/SfM/ScriptFiles/SfMvDiver Plotting Functions.R") 
source("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/Functions/Benthic_Functions_newApp_vTAOfork.R")
source("C:/Users/Courtney.S.Couch/Documents/GitHub/fish-paste/lib/core_functions.R")
library(gridExtra)
library(reshape2)
library(plyr)
library(hydroGOF)
library(tidyverse)
library(ggpmisc)
library(lme4)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(car)
library(dplyr)
library(gridExtra)
library(foreign)
library(haven)
library(knitr)
library(png)
library(grid)
library(knitr)
library(sjPlot)
library(pander)
library(kableExtra)
library(papeR)


# read in data
setwd("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/SfM/Method Comparision")
seg<-read.csv("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/SfM/Method Comparision/HARAMP19_GENUS_SEGMENT.csv")

#Select columns to keep in segment data
seg<-dplyr::select(seg, c(METHOD,SITE,SITEVISITID,SEGMENT,GENUS_CODE,ANALYST,SEGAREA_ad,SEGAREA_j,AdColCount,AdColDen,JuvColDen,Ave.size,Ave.od,Ave.rd,
                                    BLE_prev,AcuteDZ_prev,ChronicDZ_prev,ISLAND,SEC_NAME,DEPTH_BIN,LATITUDE,LONGITUDE,HABITAT_CODE,
                                    MIN_DEPTH_M,MAX_DEPTH_M))

sfm_seg<-subset(seg,METHOD=="SfM")
diver_seg<-subset(seg,METHOD=="Diver")

#Set up in wide format
colnames(sfm_seg)[9:17] <- paste("SfM_", colnames(sfm_seg[,c(9:17)]), sep = "");sfm_seg<-dplyr::select(sfm_seg,-c(METHOD,ANALYST,HABITAT_CODE))
                                                                                                                     
colnames(diver_seg)[9:17] <- paste("Diver_", colnames(diver_seg[,c(9:17)]), sep = "");diver_seg<-dplyr::select(diver_seg,-c(METHOD,ANALYST,ISLAND,HABITAT_CODE,SEC_NAME,DEPTH_BIN,LATITUDE,LONGITUDE,MIN_DEPTH_M,MAX_DEPTH_M))

seg.wide<-merge(sfm_seg,diver_seg,by=c("SITE","SITEVISITID","SEGMENT","GENUS_CODE","SEGAREA_ad","SEGAREA_j"),all=T)

#################IMPORTANT- CHECK FOR MERGING ERRORS
View(subset(seg.wide,GENUS_CODE=="SSSS")) #Make sure columns merge properly

#Merge together and remove segs that aren't merging properly
seg.wide<-merge(sfm_seg,diver_seg,by=c("SITE","SITEVISITID","SEGMENT","GENUS_CODE","SEGAREA_ad","SEGAREA_j"))
View(seg.wide) ##NOTE- LAN-01819 seg 10 SfM is duplicated for some reason-hopefully this will be fixed with final data

# #Change NAs for abunanance and density metrics to 0. Don't change NAs in the partial mortality columns to 0
seg.wide$Diver_JuvColDen[is.na(seg.wide$Diver_JuvColDen)]<-0
seg.wide$Diver_AdColDen[is.na(seg.wide$Diver_AdColDen)]<-0
seg.wide$SfM_JuvColDen[is.na(seg.wide$SfM_JuvColDen)]<-0
seg.wide$SfM_AdColDen[is.na(seg.wide$SfM_AdColDen)]<-0

head(seg.wide)

head(subset(seg.wide,GENUS_CODE=="SSSS"))

```
##Likelihood Ratio Tests


*Note: I can't get the tables to output well in word doc*    
M = Method Type  
A = Analyst  
MxA = Method Type x Analyst  
MxD = Method Type x Max Depth  
NullMod = Null Model  

###ADULT DENSITY
<p style="color:red">All Scleractinians</p> 
```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
s<-subset(seg,GENUS_CODE=="SSSS")
nullmod<-glmer(AdColCount~1 + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
M<-glmer(AdColCount~METHOD + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxA<-glmer(AdColCount~METHOD*ANALYST+ (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxD<-glmer(AdColCount~METHOD*MAX_DEPTH_M + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)

pander(anova(M,nullmod,test="chisq"))  
  
```
\newline  \newline

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxA,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxD,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE,echo=FALSE}
tab_model(M,MxA,MxD,show.ci=FALSE,show.icc = FALSE)
#tab_model(MxA,show.icc = FALSE)
#tab_model(MxD,show.icc = FALSE)

```
<p style="color:red">*Porites*</p> 

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
s<-subset(seg,GENUS_CODE=="POSP")
nullmod<-glmer(AdColCount~1 + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
M<-glmer(AdColCount~METHOD + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxA<-glmer(AdColCount~METHOD*ANALYST+ (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxD<-glmer(AdColCount~METHOD*MAX_DEPTH_M + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)

pander(anova(M,nullmod,test="chisq"))  
  
```
\newline  \newline

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxA,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxD,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE,echo=FALSE}
tab_model(M,MxA,MxD,show.ci=FALSE,show.icc = FALSE)
#tab_model(MxA,show.icc = FALSE)
#tab_model(MxD,show.icc = FALSE)

```
<p style="color:red">*Montipora*</p> 

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
s<-subset(seg,GENUS_CODE=="MOSP")
nullmod<-glmer(AdColCount~1 + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
M<-glmer(AdColCount~METHOD + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxA<-glmer(AdColCount~METHOD*ANALYST+ (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxD<-glmer(AdColCount~METHOD*MAX_DEPTH_M + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)

pander(anova(M,nullmod,test="chisq"))  
  
```
\newline  \newline

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxA,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxD,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE,echo=FALSE}
tab_model(M,MxA,MxD,show.ci=FALSE,show.icc = FALSE)
#tab_model(MxA,show.icc = FALSE)
#tab_model(MxD,show.icc = FALSE)

```
<p style="color:red">*Pocillopora*</p> 

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
s<-subset(seg,GENUS_CODE=="POCS")
nullmod<-glmer(AdColCount~1 + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
M<-glmer(AdColCount~METHOD + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxA<-glmer(AdColCount~METHOD*ANALYST+ (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)
MxD<-glmer(AdColCount~METHOD*MAX_DEPTH_M + (1|SEC_NAME/SITE)+ offset(SEGAREA_ad),family=poisson,data=s)

pander(anova(M,nullmod,test="chisq"))  
  
```
\newline  \newline

```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxA,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE, echo = FALSE,fig.width=8, fig.height=7}
pander(anova(MxD,nullmod,test="chisq"))

```
```{r, warning = FALSE, message = FALSE,echo=FALSE}
tab_model(M,MxA,MxD,show.ci=FALSE,show.icc = FALSE)
#tab_model(MxA,show.icc = FALSE)
#tab_model(MxD,show.icc = FALSE)

```