#This script was originally generated by Tom Oliver and updated by Courtney Couch
#This is a power analysis to detect significant methodological bias assuming a 2-tailed t-test, the standard deviation of the metric (adult density, juvenile density, average colony diameter, and average old dead were transformed then back transformed, the remaining metrics were untranformed), power of 0.8, ?? = 0.05, and an N from 3 to 1000 samples. 
rm(list=ls())

library(ggplot2)
library(gridExtra)
library(tidyverse)
library(tidyr)
library(dplyr)
Belt=read.csv("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/SfM/Method Comparision/HARAMP19_GENUS_SITE.csv")
BeltDiv=read.csv("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/SfM/Method Comparision/HARAMP19_DIVERSITY_SPECIES_SITE.csv")

#Subset total hard corals and merge belt and diversity data together
tmp=subset(Belt,GENUS_CODE=="SSSS")
BeltDiv$GENUS_CODE="SSSS"
SSSS<-left_join(tmp,BeltDiv)

#Identify which metrics to use
targets=c("AdColDen","JuvColDen","Ave.size","Ave.od",
          "Ave.rd","AcuteDZ_prev","ChronicDZ_prev","BLE_prev",
          "Adult_Shannon","Adult_Richness")

#Identify which metrics we want for the report and manuscript- they differ
targets_report=targets[c(1:8)]
targets_manu=targets[c(1:4,8:10)]

#Set up transformations
targetstrans=c("sqrt","sqrt","log","sqrt",
               " "," "," "," ",
               " "," ")
targetsplot=c("Adult Colony Density","Juvenile Colony Density","Average Colony Diameter","Average Old Dead",
              "Average Recent Dead","Acute Disease Prevelance","Chronic Disease Prevelance","Bleaching Prevelance",
              "Adult Shannon Diversity","Adult Species Richness")
tpLU=targetsplot
names(tpLU)=targets
ttLU=targetstrans
names(ttLU)=targets
utLU=c(" ","sq","exp");names(utLU)=c(" ","sqrt","log")
sq=function(x){return(x^2)}


#all look like we should use a sqrt transform (though log could be better for size...)
#but we will mirror the transforms used for the analysis
#Conduct the power analysis
tarDF=NULL
for(t in 1:length(targets)){
  DF=data.frame(N=seq(3,350,by=1),delta=NA,var=targets[t],plotvar=targetsplot[t],stringsAsFactors = F)
  SSSS$Y=(SSSS[,c(targets[t])])
  eval(parse(text=paste0("SSSS$Yt=",ttLU[targets[t]],"(SSSS$Y+.01)")))
  for (i in 1:nrow(DF)){
    Yt=power.t.test(sd = sd(SSSS$Yt,na.rm=T),n = DF$N[i],
                    sig.level = 0.05,power = 0.8)
    DF$delta[i]=Yt$delta
    eval(parse(text=paste0("DF$deltaUT[i]=",utLU[ttLU[targets[t]]],"(Yt$delta)")))
    print(paste(targets[t],"N=",DF$N[i]))
  }
  tarDF=rbind(tarDF,DF)
  #plotlist[[t]]=ggplot(DF,aes(N,delta/meanDF$N,DF$delta/mean(SfM$Y,na.rm=T),log="x",ylab="Percent Effect Size",type="l")
}

#Functions
sq=function(x){return(x^2)}
se=function(x){return(sd(x,na.rm=T)/sqrt(length(x)))}
CoV=function(x){return(se(x)/mean(x,na.rm=T))}
CI95=function(x){return(1.96*se(x))}
Nnona=function(x){return(length(x[!is.na(x)]))}

#Calculate Transformed Summary Stats
SSSSsum1=SSSS[,c("METHOD","SITE","SITEVISITID","GENUS_CODE",targets)]%>%
  filter(GENUS_CODE=="SSSS",METHOD=="SfM") %>%
  pivot_longer(cols = all_of(targets),
               names_to = "Var",values_to = "Values") %>%
  mutate(Transform=ttLU[Var]) %>%
  mutate(BackTransform=utLU[Transform])

SSSSsum1$TransValues=NA
for(i in 1:nrow(SSSSsum1)){
  eval(parse(text=paste0("SSSSsum1$TransValues[i]=",SSSSsum1$Transform[i],"(",SSSSsum1$Values[i],")")))
}

SSSSsum=SSSSsum1%>%
  group_by(Var) %>%
  summarise(N=Nnona(TransValues),sd=sd(TransValues,na.rm=T),se=se(TransValues),CoV=CoV(TransValues))
SSSSsum$Back_Transform=utLU[ttLU[SSSSsum$Var]]

SSSSsum$sd_bt=NA;SSSSsum$se_bt=NA;
for(i in 1:nrow(SSSSsum)){
  eval(parse(text=paste0("SSSSsum$sd_bt[i]=",SSSSsum$Back_Transform[i],"(",SSSSsum$sd[i],")")))
  eval(parse(text=paste0("SSSSsum$se_bt[i]=",SSSSsum$Back_Transform[i],"(",SSSSsum$se[i],")")))
}

#Calculate Transformed Delta
SSSSdelta1=SSSS[c("METHOD","SITE","SITEVISITID","GENUS_CODE",targets)]%>%
  filter(GENUS_CODE=="SSSS")%>%
  pivot_longer(cols = all_of(targets),
               names_to = "Var",values_to = "Values")%>%
  mutate(Transform=ttLU[Var]) %>%
  mutate(BackTransform=utLU[Transform])

SSSSdelta1$TransValues=NA
for(i in 1:nrow(SSSSdelta1)){
  eval(parse(text=paste0("SSSSdelta1$TransValues[i]=",SSSSdelta1$Transform[i],"(",SSSSdelta1$Values[i],")")))
}


SSSSdelta2=SSSSdelta1[,c("METHOD","SITE","SITEVISITID","Var","Transform","BackTransform","TransValues")]%>%
  pivot_wider(names_from=METHOD,values_from=TransValues)%>%
  mutate(Delta=SfM-Diver)

SSSSdelta2$BackDelta=NA
for(i in 1:nrow(SSSSdelta2)){
  eval(parse(text=paste0("SSSSdelta2$BackDelta[i]=",SSSSdelta2$BackTransform[i],"(",SSSSdelta2$Delta[i],")")))
}

#Calculate MAE measured in the study to include in the plot
SSSSdelta=SSSSdelta2%>%
  group_by(Var)%>%
  summarize(N=Nnona(Delta),MAE=mean(abs(Delta),na.rm=T),SE_AE=se(abs(Delta)),CI_AE=CI95(abs(Delta)),
            Nb=Nnona(BackDelta),MAEb=mean(abs(BackDelta),na.rm=T),SE_AEb=se(abs(BackDelta)),CI_AEb=CI95(abs(BackDelta)))

SSSSp=right_join(SSSSdelta,SSSSsum,by="Var")  
SSSSp$plotvar=tpLU[SSSSp$Var]
head(SSSSp)

PowLev=subset(tarDF,N==104)
names(PowLev)=c("N.pow","delta.pow","Var","plotvar","deltaBT.pow")
SSSSp=right_join(SSSSp,PowLev,by=c("Var","plotvar"))  
SSSSp$EffSizeSD=SSSSp$deltaBT.pow/SSSSp$sd_bt #Calcuate effect size
names(PowLev)=c("N","delta","Var","plotvar","deltaBT")


#Set order of variables
tarDF$plotvar=factor(tarDF$plotvar,levels=c("Adult Colony Density","Juvenile Colony Density",
                                            "Average Colony Diameter","Average Old Dead","Average Recent Dead",
                                            "Acute Disease Prevelance","Chronic Disease Prevelance",
                                            "Bleaching Prevelance","Adult Shannon Diversity","Adult Species Richness"))
SSSSp$plotvar=factor(SSSSp$plotvar,levels=c("Adult Colony Density","Juvenile Colony Density",
                                            "Average Colony Diameter","Average Old Dead","Average Recent Dead",
                                            "Acute Disease Prevelance","Chronic Disease Prevelance",
                                            "Bleaching Prevelance","Adult Shannon Diversity","Adult Species Richness"))

#Plot for manuscript
PowerMAE_manu=ggplot(data=subset(tarDF,var%in%targets_manu),aes(N,deltaUT))+
  geom_line()+
  geom_point(data=subset(SSSSp,Var%in%targets_manu),aes(N.pow,deltaBT.pow),shape=1,size=3)+
  geom_point(data=subset(SSSSp,Var%in%targets_manu),aes(N.x,MAEb),shape=0,size=3)+
#  geom_errorbar(data=SSSSp,aes(x=N.x,y=MAE,
#                              ymin=(MAE-CI_AE),ymax=(MAE+CI_AE)))+
  facet_wrap(.~plotvar,scales="free_y")+
  scale_x_continuous()+
  scale_y_continuous()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  xlab("Sample Size")+ylab("Power Analysis Effect Size : MAE")

ggsave(plot = PowerMAE_manu,filename = "T:/Benthic/Data/SfM/Method Comparision/Figures/PowerCurves_Manuscript.jpg",
       width=6.5,height=6.5)             

#plot for report
PowerMAE_rep=ggplot(data=subset(tarDF,var%in%targets_report),aes(N,deltaUT))+
  geom_line()+
  geom_point(data=subset(SSSSp,Var%in%targets_report),aes(N.pow,deltaBT.pow),shape=1,size=3)+
  geom_point(data=subset(SSSSp,Var%in%targets_report),aes(N.x,MAEb),shape=0,size=3)+
  #  geom_errorbar(data=SSSSp,aes(x=N.x,y=MAE,
  #                              ymin=(MAE-CI_AE),ymax=(MAE+CI_AE)))+
  facet_wrap(.~plotvar,scales="free_y")+
  scale_x_continuous()+
  scale_y_continuous()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  xlab("Sample Size")+ylab("Power Analysis Effect Size : MAE")

ggsave(plot = PowerMAE_rep,filename = "T:/Benthic/Data/SfM/Method Comparision/Figures/PowerCurves_Report.jpg",
       width=6.5,height=6.5)     



# Power analysis for dominant coral genera --------------------------------

#Subset Dominant taxa then reformat dataframe to list columns by genus_metric
GEN_sub<-subset(Belt,GENUS_CODE %in% c("POSP","MOSP","POCS"))
GEN_ad=GEN_sub[c(1:3,5,7)]
GEN_ad<-spread(GEN_ad,GENUS_CODE,AdColDen)
colnames(GEN_ad)[4:6] <- paste(colnames(GEN_ad)[4:6], "AdColDen", sep = "_")
GEN_j=GEN_sub[c(1:3,5,10)]
GEN_j<-spread(GEN_j,GENUS_CODE,JuvColDen)
colnames(GEN_j)[4:6] <- paste(colnames(GEN_j)[4:6], "JuvColDen", sep = "_")

GEN<-left_join(GEN_ad,GEN_j);head(GEN)

targets=c("POSP_AdColDen","POSP_JuvColDen","MOSP_AdColDen","MOSP_JuvColDen","POCS_AdColDen","POCS_JuvColDen")
targetstrans=c("sqrt","sqrt"," "," "," "," ")
targetsplot=c("Porites Adult Density","Porites Juvenile Density","Monitpora Adult Density","Montipora Juvenile Density",
              "Pocillopora Adult Density","Pocillopora Juvenile Density")
tpLU=targetsplot
names(tpLU)=targets
ttLU=targetstrans
names(ttLU)=targets
utLU=c(" ","sq","exp");names(utLU)=c(" ","sqrt","log")
sq=function(x){return(x^2)}


#all look like we should use a sqrt transform (though log could be better for size...)
tarGEN=NULL
for(t in 1:length(targets)){
  DF=data.frame(N=seq(3,350,by=1),delta=NA,var=targets[t],plotvar=targetsplot[t],stringsAsFactors = F)
  GEN$Y=(GEN[,c(targets[t])])
  eval(parse(text=paste0("GEN$Yt=",ttLU[targets[t]],"(GEN$Y+.01)")))
  for (i in 1:nrow(DF)){
    Yt=power.t.test(sd = sd(GEN$Yt,na.rm=T),n = DF$N[i],
                    sig.level = 0.05,power = 0.8)
    DF$delta[i]=Yt$delta
    eval(parse(text=paste0("DF$deltaUT[i]=",utLU[ttLU[targets[t]]],"(Yt$delta)")))
    print(paste(targets[t],"N=",DF$N[i]))
  }
  tarGEN=rbind(tarGEN,DF)
}


GENsum1=GEN[,c("METHOD","SITE","SITEVISITID",targets)]%>%
  filter(METHOD=="SfM") %>%
  pivot_longer(cols = all_of(targets),
               names_to = "Var",values_to = "Values") %>%
  mutate(Transform=ttLU[Var]) %>%
  mutate(BackTransform=utLU[Transform])

GENsum1$TransValues=NA
for(i in 1:nrow(GENsum1)){
  eval(parse(text=paste0("GENsum1$TransValues[i]=",GENsum1$Transform[i],"(",GENsum1$Values[i],")")))
}

GENsum=GENsum1%>%
  group_by(Var) %>%
  summarise(N=Nnona(TransValues),sd=sd(TransValues,na.rm=T),se=se(TransValues),CoV=CoV(TransValues))
GENsum$Back_Transform=utLU[ttLU[GENsum$Var]]

GENsum$sd_bt=NA;GENsum$se_bt=NA;
for(i in 1:nrow(GENsum)){
  eval(parse(text=paste0("GENsum$sd_bt[i]=",GENsum$Back_Transform[i],"(",GENsum$sd[i],")")))
  eval(parse(text=paste0("GENsum$se_bt[i]=",GENsum$Back_Transform[i],"(",GENsum$se[i],")")))
}

#Calculate Transformed Delta
GENdelta1=GEN[c("METHOD","SITE","SITEVISITID",targets)]%>%
  pivot_longer(cols = all_of(targets),
               names_to = "Var",values_to = "Values")%>%
  mutate(Transform=ttLU[Var]) %>%
  mutate(BackTransform=utLU[Transform])

GENdelta1$TransValues=NA
for(i in 1:nrow(GENdelta1)){
  eval(parse(text=paste0("GENdelta1$TransValues[i]=",GENdelta1$Transform[i],"(",GENdelta1$Values[i],")")))
}


GENdelta2=GENdelta1[,c("METHOD","SITE","SITEVISITID","Var","Transform","BackTransform","TransValues")]%>%
  pivot_wider(names_from=METHOD,values_from=TransValues)%>%
  mutate(Delta=SfM-Diver)

GENdelta2$BackDelta=NA
for(i in 1:nrow(GENdelta2)){
  eval(parse(text=paste0("GENdelta2$BackDelta[i]=",GENdelta2$BackTransform[i],"(",GENdelta2$Delta[i],")")))
}

GENdelta=GENdelta2%>%
  group_by(Var)%>%
  summarize(N=Nnona(Delta),MAE=mean(abs(Delta),na.rm=T),SE_AE=se(abs(Delta)),CI_AE=CI95(abs(Delta)),
            Nb=Nnona(BackDelta),MAEb=mean(abs(BackDelta),na.rm=T),SE_AEb=se(abs(BackDelta)),CI_AEb=CI95(abs(BackDelta)))

GENp=right_join(GENdelta,GENsum,by="Var")  
GENp$plotvar=tpLU[GENp$Var]
head(GENp)

PowLev=subset(tarGEN,N==104)
names(PowLev)=c("N.pow","delta.pow","Var","plotvar","deltaBT.pow")
GENp=right_join(GENp,PowLev,by=c("Var","plotvar"))  
GENp$EffSizeSD=GENp$deltaBT.pow/GENp$sd_bt
names(PowLev)=c("N","delta","Var","plotvar","deltaBT")



#
tarGEN$plotvar=factor(tarGEN$plotvar,levels=c("Porites Adult Density","Porites Juvenile Density","Monitpora Adult Density","Montipora Juvenile Density",
                                              "Pocillopora Adult Density","Pocillopora Juvenile Density"))
GENp$plotvar=factor(GENp$plotvar,levels=c("Porites Adult Density","Porites Juvenile Density","Monitpora Adult Density","Montipora Juvenile Density",
                                          "Pocillopora Adult Density","Pocillopora Juvenile Density"))

#Change labels to italicize Genus name
levels(tarGEN$plotvar)=c("italic('Porites')*' Adult Density'","italic('Porites')*' Juvenile Density'","italic('Montipora')*' Adult Density'","italic('Monitpora')*' Juvenile Density'",
                         "italic(Pocillopora)*' Adult Density'","italic(Pocillopora)*' Juvenile Density'")
levels(GENp$plotvar)=c("italic('Porites')*' Adult Density'","italic('Porites')*' Juvenile Density'","italic('Montipora')*' Adult Density'","italic('Monitpora')*' Juvenile Density'",
                       "italic(Pocillopora)*' Adult Density'","italic(Pocillopora)*' Juvenile Density'")


PowerMAE_GEN=ggplot(data=tarGEN,aes(N,delta))+
  geom_line()+
  geom_point(data=GENp,aes(N.pow,delta.pow),shape=1,size=3)+
  geom_point(data=GENp,aes(N.x,MAE),shape=0,size=3)+
  #  geom_errorbar(data=SSSSp,aes(x=N.x,y=MAE,
  #                              ymin=(MAE-CI_AE),ymax=(MAE+CI_AE)))+
  facet_wrap(.~plotvar,scales="free_y",labeller = label_parsed)+
  scale_x_continuous()+
  scale_y_continuous()+
  theme_bw()+xlab("Sample Size")+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank())+
  ylab("Power Analysis Effect Size : MAE")
ggsave(plot = PowerMAE_GEN,filename = "T:/Benthic/Data/SfM/Method Comparision/Figures/PowerCurves_Genera.jpg",
       width=6.5,height=5)             


