#This script QCs the benthic REA data pulled directly from the reports that are generated by the mission application.
#It is designed to help flag errors to be corrected directly in the mission app.
#Created by Courtney Couch 5/23/19
rm(list=ls())

#LOAD LIBRARY FUNCTIONS ... 
source("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/Functions/Benthic_Functions_BSR.R")
source("C:/Users/Courtney.S.Couch/Documents/GitHub/fish-paste/lib/core_functions.R")


## LOAD benthic data
setwd("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/SfM")
x<-read.table("OAH_SfM_pilot.txt",header=TRUE,sep=",") #read geodatabase exported from Arc
head(x)

#Create vector of column names to include then exclude unwanted columns from dataframe
DATA_COLS<-c("ANALYST","OBS_YEAR","MISSIONS_ID","SITE","SEGMENT","SEGLENGTH",
             "SEGWIDTH","NO_COLONY_OBSERVED","SPCODE","FRAGMENT","MORPH_CODE","OLD DEAD",
             "RDCAUSE1","RD_1","RDCAUSE2","RD_2","RDCAUSE3","RD_3","CON_1","EXTENT_1","SEV_1",
             "CON_2","EXTENT_2","SEV_1","CON_3","EXTENT_3","SEV_3")


#remove extraneous columns
head(x[,DATA_COLS])
x<-x[,DATA_COLS]
sort(colnames(x))

colnames(x)[colnames(x)=="RD_1"]<-"RDEXTENT1" #Change column name
colnames(x)[colnames(x)=="RDCAUSE1"]<-"RD1" #Change column name
colnames(x)[colnames(x)=="RECENTDEAD_2"]<-"RDEXTENT2" #Change column name
colnames(x)[colnames(x)=="RECENT_SPECIFIC_CAUSE_CODE_2"]<-"RD2" #Change column name
colnames(x)[colnames(x)=="RECENT_SPECIFIC_CAUSE_CODE_3"]<-"RD3" #Change column name
colnames(x)[colnames(x)=="FRAGMENT_YN"]<-"Fragment" #Change column name
colnames(x)[colnames(x)=="GENCODE"]<-"GENUS_CODE" #Change column name





# Prepare dataset ---------------------------------------------------------

#Add a colony id (temporary)
x$COLONYID<-seq(1:length(x$COLONYID))

#Add column to indicate adult or juvenile
x$ad_juv<-ifelse(x$COLONYLENGTH<5 & x$FRAGMENT=="0","JUVENILE","ADULT")

#Add Transect column
x$TRANSECT<-1


# Prepping Adult Data -----------------------------------------------------

#merge in the no colony segments
#x<-merge(ad,segad,by=c("SITE","DIVER","ISLAND","TRANSECT","SEGMENT","SEGLENGTH","SEGWIDTH","REEF_ZONE","DEPTH_BIN","SITE_MIN_DEPTH","SITE_MAX_DEPTH"),all=TRUE)

ad$SITE<-SiteNumLeadingZeros(ad$SITE) # Change site number such as MAR-22 to MAR-0022


### Use these functions to look at data
head(ad)
tail(ad)
sort(colnames(ad))

#Create vector of column names to include then exclude unwanted columns from dataframe
#NOTE- I REMOVED RECENTDEAD_3 FOR NOW BECAUSE IT'S NOT IN THE APP REPORT
DATA_COLS<-c("MISSIONID","REGION_NAME","ISLAND","SITE","LATITUDE",	"LONGITUDE","REEF_ZONE","DEPTH_BIN","OBS_YEAR",
             "DATE_","SITEVISITID","HABITAT_CODE","DIVER","TRANSECT","SEGMENT","SEGWIDTH","SEGLENGTH",
             "COLONYID","Taxoncode","MORPH_CODE","COLONYLENGTH","OLDDEAD",
             "RECENTDEAD","RECENT_GENERAL_CAUSE_CODE","RECENT_SPECIFIC_CAUSE_CODE",
             "RECENTDEAD_2",	"RECENT_GENERAL_CAUSE_CODE_2","RECENT_SPECIFIC_CAUSE_CODE_2",	
             "RECENT_GENERAL_CAUSE_CODE_3","RECENT_SPECIFIC_CAUSE_CODE_3","CONDITION_1",
             "CONDITION_2","CONDITION_3","EXTENT","EXTENT_2","EXTENT_3","SEVERITY","SEVERITY_2","SEVERITY_3",
             "GENUS_CODE","S_ORDER","TAXONNAME","SITE_MIN_DEPTH","SITE_MAX_DEPTH")

#remove extraneous columns
head(ad[,DATA_COLS])
ad<-ad[,DATA_COLS]

##Change column names to make code easier to code
colnames(ad)[colnames(ad)=="Taxoncode"]<-"SPCODE" #Change column name
colnames(ad)[colnames(ad)=="RECENTDEAD"]<-"RDEXTENT1" #Change column name
colnames(ad)[colnames(ad)=="RECENT_GENERAL_CAUSE_CODE"]<-"GENRD1" #Change column name
colnames(ad)[colnames(ad)=="RECENT_SPECIFIC_CAUSE_CODE"]<-"RD1" #Change column name
colnames(ad)[colnames(ad)=="RECENTDEAD_2"]<-"RDEXTENT2" #Change column name
colnames(ad)[colnames(ad)=="RECENT_GENERAL_CAUSE_CODE_2"]<-"GENRD2" #Change column name
colnames(ad)[colnames(ad)=="RECENT_SPECIFIC_CAUSE_CODE_2"]<-"RD2" #Change column name
colnames(ad)[colnames(ad)=="RECENT_GENERAL_CAUSE_CODE_3"]<-"GENRD3" #Change column name
colnames(ad)[colnames(ad)=="RECENT_SPECIFIC_CAUSE_CODE_3"]<-"RD3" #Change column name

head(ad)


#Change NAs in the Taxon and genus code to AAAA
ad$GENUS_CODE<-as.character(ad$GENUS_CODE)
ad$SPCODE<-as.character(ad$SPCODE)

ad$GENUS_CODE[is.na(ad$GENUS_CODE)]<-"AAAA"#change nas to AAAA
ad$SPCODE[is.na(ad$SPCODE)]<-"AAAA"#change nas to AAAA

utils::View(ad) #view data in separate window


##Calcuating segment and transect area and add column for transect area
x<-Transectarea(ad)
sapply(ad,levels)
head(ad)
nrow(ad)



# Prep Juvenile data ------------------------------------------------------

## CREATE JUVENILE CLEAN ANALYSIS READY DATA ----
j<-read.csv("leg2_juveniles.csv")#read in juvenile data
#segjuv<-subset(seg,Method=="JUVENILE")

#Create colony id that doesn't overlap with adults
j$temp<-seq(1:length(j$COLONYID))
j$COLONYID<-j$temp+5029


#merge juv and segments together
#j<-merge(juv,segjuv,by=c("OBS_YEAR","MISSIONID","SITE","SITEVISITID","LATITUDE","DIVER",	"LONGITUDE","ISLAND","TRANSECT","SEGMENT","SEGLENGTH","SEGWIDTH","REEF_ZONE","DEPTH_BIN"),all=TRUE)

j$SITE<-SiteNumLeadingZeros(j$SITE)

sort(colnames(j))
#Create vector of column names to include then ejclude unwanted columns from dataframe
DATA_COLS<-c("MISSIONID","REGION_NAME","ISLAND","SITE","LATITUDE",	"LONGITUDE","REEF_ZONE","DEPTH_BIN","OBS_YEAR",
             "DATE_","SITEVISITID","HABITAT_CODE","DIVER","TRANSECTNUM","SEGMENT","SEGWIDTH",
             "SEGLENGTH","COLONYID","Taxoncode","COLONYLENGTH","GENUS","S_ORDER","MIN_DEPTH","MAX_DEPTH")

head(j[,DATA_COLS])
j<-j[,DATA_COLS]



##Change column names to make code easier to code
colnames(j)[colnames(j)=="SPECIES"]<-"SPCODE" #Change column name
colnames(j)[colnames(j)=="TRANSECTNUM"]<-"TRANSECT" #Change column name
colnames(j)[colnames(j)=="MIN_DEPTH"]<-"SITE_MIN_DEPTH" #Change column name
colnames(j)[colnames(j)=="MAX_DEPTH"]<-"SITE_MAX_DEPTH" #Change column name

#Change NAs in Genus and SPCODE to AAAA 
j$GENUS_CODE[j$GENUS_CODE=="-"]<-NA 
j$GENUS_CODE<-as.character(j$GENUS_CODE)
j$SPCODE<-as.character(j$SPCODE)

#Change NA to AAAA to ensure you keep the 0s in
j$GENUS_CODE[is.na(j$GENUS_CODE)]<-"AAAA"#change nas to AAAA
j$SPCODE[is.na(j$SPCODE)]<-"AAAA"#change nas to AAAA

utils::View(j) #view data in separate window


##Calcuating segment and transect area and add column for transect area
j<-Transectarea(j)
sapply(j,levels)
head(j)
nrow(j)


# QC Checks ---------------------------------------------------------------
#Set up output csv file that reports the status of the qc checks
output<-data.frame(
  QC_check<-character(),
  Status<-character(),stringsAsFactors = FALSE)

output<-data.frame(
  QC_check,
  Status,stringsAsFactors = FALSE)


#1. Check that all data has been QC'd. If the following code returns records then there are segments that have not been QC'd
ad[ad$QC=="-",]
j[j$QC=="-",]
output[1,]<-c("Data have been QC'd","ok")


#2. Check number of sites is correct
ddply(ad,.(ISLAND),summarize,temp=length(unique(SITE)))
output[2,]<-c("Number of sites is correct","ok")


#3. Benthic and fish sites do not overlap
fish<-read.csv(fish_sitevisit.csv)
test<-merge(sv[,Site,Island],fish[,Site,Island],by=c("Site","Island"))
test #sites that appear in this list are overlapping and should be discussed with the fish team and corrected with Michael

output[3,]<-c("Benthic and fish sites do not overlap","ok")


#4. Make sure that all sites have all segments. If segments are missing double check datasheets and keep a record of segments that weren't surveyed
#Also check for duplicate segments (multiple divers entered segment- there should only be 1 segment record/site)
test<-ddply(ad,.(SITE,SEGMENT,DIVER),summarize,temp=length(SEGMENT))
test<-ddply(test,.(SITE,SEGMENT),summarize,count=length(SEGMENT))

# if there are multiple segment entries for a given this needs to be fixed
test[test$count>1,] 

#Create a list of sites that have <=2 segments to double check that all segments were entered
test<-ddply(ad,.(SITE),summarize,count=length(unique(SEGMENT)))
test[test$count<3,] 

output[4,]<-c("All sites have all segments & no duplicate segments",NA)

#5. Check that depths are not null and Add a new column to sitevisit table and flags any sites that don't match depth ranges for a given depth bin
summary(sv$Max.depth)
summary(sv$Min.depth)

sv$db_ok<-NULL
for (i in c(1:nrow(sv))){ #opening brace
  if(sv$Depth.bin[i] =="Deep"& sv$Min.depth[i]>=60){ #c&p
    sv$db_ok[i] = "ok" #c&p
  } #c&p
  if(sv$Depth.bin[i] =="Mid"& sv$Min.depth[i]>20&sv$Max.depth[i]<60){ #c&p
    sv$db_ok[i] = "ok" #c&p
  } #c&p
  if(sv$Depth.bin[i] =="Shallow"& sv$Max.depth[i]<=20){ #c&p
    sv$db_ok[i] = "ok" #c&p
  } #c&p
} #closing curly brace for entire forloop

sv$db_ok[is.na(sv$db_ok)]<-"error"
subset(sv,db_ok=="error") #identify the sites that have incorrect depth bins

output[5,]<-c("Depth Bins Match site Depths","Send list to Michael of sites to fix")

#6. Any sites that have transects other than 1
ad[ad$TRANSECT!="1",]
j[j$TRANSECT!="1",]

output[6,]<-c("Transect number = 1","ok")

#check for sites that don't have transect photos

#7.Check for incorrect species
ddply(ad,.(DIVER,GENUS_CODE,Taxoncode),summarize,temp=length(Taxoncode))

output[7,]<-c("Species codes are correct","ok")

#8.That the columns have the appropripate type of data (e.g. numeric vs. text) & no errant codes (e.g. ble instead of BLE)
sapply(ad,levels)

output[8,]<-c("No errant codes","ask MA to change - to 0 in frag column, change dama to damg")

#9. Identify colonies <5cm in the adult database but not fragments (Fragments indicated as 0% recent dead and DAMB)
ad[ad$Fragment.yn!="-1"&ad$COLONYLENGTH<5&ad$Taxoncode!="PBER",]

output[9,]<-c("No adult colonies less than 5cm that aren't fragments","ok")


#11. Identify juvenile colonies that are >= 5cm
j[j$COLONY_LENGTH>=5]

output[11,]<-c("Juvenile size range is correct","NA","ok")


#12.Identify colonies with 0% recent dead, but PRED or DZGEN as general cause code- This check should result in 0 records
ad[ad$RDEXTENT1=="0"& ad$GENRD1!="-",]
ad[ad$RDEXTENT1=="0"& ad$RD1!="-",]
ad[ad$RDEXTENT2=="0"& ad$GENRD2!="-",]
ad[ad$RDEXTENT2=="0"& ad$RD2!="-",]
ad[ad$RDEXTENT3=="0"& ad$GENRD3!="-",]
ad[ad$RDEXTENT3=="0"& ad$RD3!="-",]
ad[ad$EXTENT_1=="0"& ad$CONDITION_1!="-",]
ad[ad$EXTENT_2=="0"& ad$CONDITION_2!="-",]
ad[ad$EXTENT_3=="0"& ad$CONDITION_3!="-",]

output[12,]<-c("Recent Dead cause is present, but %RD = 0","ok")

#13.Identify colonies with 0% recent dead, but PRED or DZGEN as general cause code- This check should result in 0 records
ad[ad$GENRD1!="-"& ad$RDEXTENT1=="-",]
ad[ad$GENRD2!="-"& ad$RDEXTENT2=="-",]
ad[ad$GENRD3!="-"& ad$RDEXTENT3=="-",]

output[13,]<-c("% Recent dead included if a cause was recorded","ok")

#14. Identify colonies with NO % recent dead. Double check that these shouldn't be 0
ad[ad$RDEXTENT1=="-",]
ad[ad$RDEXTENT2=="-",]
ad[ad$RDEXTENT3=="-",]

output[14,]<-c("No missing %RD values","ask MA EXTENTs - to 0")

#15. Identify colonies with NO % EXTENT, but a condition. Double check that these shouldn't be 0
ad[ad$EXTENT=="-"& ad$CONDITION_1!="-",]
ad[ad$EXTENT_2=="-"& ad$CONDITION_2!="-",]
ad[ad$EXTENT_3=="-"& ad$CONDITION_3!="-",]

output[15,]<-c("All colonies with a condition have extent","ok")


#16. Identify colonies with nothing in condition column, but a value in extent
ad[ad$CONDITION_1=="-"& ad$EXTENT!="-",]
ad[ad$CONDITION_2=="-"& ad$EXTNET_2!="-",]
ad[ad$CONDITION_3=="-"& ad$EXTENT_3!="-",]

output[16,]<-c("Identify colonies with nothing in condition column, but a value in extent","ok")

#17. Identify colonies with NO % EXTENT, but a condition. Double check that these shouldn't be 0
ad[ad$CONDITION_1=="-"& ad$SEVERITY!="-",]
ad[ad$CONDITION_2=="-"& ad$SEVERITY_2!="-",]
ad[ad$CONDITION_3=="-"& ad$SEVERITY_3!="-",]

output[17,]<-c("Identify colonies with nothing in condition column, but a value in severity","ok")

#18. Identify colonies with NO % SEVERITY, but a condition. Double check that these shouldn't be 0
ad[ad$SEVERITY=="-"& ad$CONDITION_1 %in% c("BLE","BLP"),]
ad[ad$SEVERITY2=="-"& ad$CONDITION_2%in% c("BLE","BLP"),]
ad[ad$SEVERITY3=="-"& ad$CONDITION_3%in% c("BLE","BLP"),]

#If these should be 0 then ask Michael to change them- it's faster than doing it manually

output[18,]<-c("BLE cause is present, but severity is null","ok")

#19. RD + OD is not greater than 100%
ad$totaldead<=ad$RDEXENT1+ad$RDEXTENT2+ad$RDEXTENT3+ad$OLDDEAD
ad[ad$totaldead>100]

output[19,]<-c("RD + OD <=100%",NA)

#20. Make sure that "No.colony.observed" is either 0 or -1, there were cases where there was -, which should have been 0. This is a glitch in the app. Michael fixed it?

output[20,]<-c("No colony observed column is 0 or -1",NA)


#21 Create maps of sites and confirm there are no errant sites
#for now import the site visit table into Arc.I'm working on a script to do this directly in R

output[21,]<-c("Site coordinates look good","ok")

#Export QC output table
write.csv(output,"HARAMP2019_Leg1QC_output.csv")
