#This script QCs the benthic REA data pulled directly from the reports that are generated by the mission application.
#It is designed to help flag errors to be corrected directly in the mission app.
#Created by Courtney Couch 5/23/19

#setwd("C:/Users/Courtney.S.Couch/Documents/Courtney's Files/R Files/ESD/HARAMP2019")
setwd("//pickingfish/users/Brittany.Huntington/Desktop/HARAMP Benthic QC")

#LOAD LIBRARY FUNCTIONS ... 
library(tidyr)
library(reshape2)
library(dplyr)



#source("C:/Users/Courtney.S.Couch/Documents/GitHub/Benthic-Scripts/Functions/Benthic_Functions_BSR.R")
#source("C:/Users/Courtney.S.Couch/Documents/GitHub/fish-paste/lib/core_functions.R")
source("G:/Documents/GitHub/Benthic-Scripts/Functions/Benthic_Functions_BSR.R")
source("fish-paste/lib/core_functions.R")


##read benthic data downloaded from Mission app and subset to the leg you need to QC
ad<-read.csv("adult_data.csv") #read in adult data
j<-read.csv("juv_data.csv") #read in adult data


ad <- ad %>% filter (MISSIONID == "SE1902_MHI_LEG2")
j <- j %>% filter (MISSIONID == "SE1902_MHI_LEG2")

#Add a colony id (temporary)
ad$COLONYID<-seq(1:length(ad$COLONYID))

# Prepping Adult Data -----------------------------------------------------

ad$SITE<-SiteNumLeadingZeros(ad$SITE) # Change site number such as MAR-22 to MAR-0022

### Use these functions to look at data
head(ad)
tail(ad)
sort(colnames(ad))
View(ad)


#Create vector of column names to include then exclude unwanted columns from dataframe
#NOTE- REMOVED RECENTDEAD_3s columns not present in mission app report datafile
DATA_COLS<-c("MISSIONID","REGION_NAME","ISLAND","SITE","LATITUDE",	"LONGITUDE","REEF_ZONE","DEPTH_BIN","OBS_YEAR",
             "DATE_","SITEVISITID","HABITAT_CODE","DIVER","TRANSECT","SEGMENT","SEGWIDTH","SEGLENGTH",
             "COLONYID","Taxoncode","MORPH_CODE","COLONYLENGTH","OLDDEAD","Fragment.yn",
             "RECENTDEAD","RECENT_GENERAL_CAUSE_CODE","RECENT_SPECIFIC_CAUSE_CODE",
             "RECENTDEAD_2",	"RECENT_GENERAL_CAUSE_CODE_2","RECENT_SPECIFIC_CAUSE_CODE_2",	
             "RECENT_GENERAL_CAUSE_CODE_3","RECENT_SPECIFIC_CAUSE_CODE_3","CONDITION_1",
             "CONDITION_2","CONDITION_3","EXTENT","EXTENT_2","EXTENT_3","SEVERITY","SEVERITY_2","SEVERITY_3",
             "GENUS_CODE","S_ORDER","TAXONNAME","SITE_MIN_DEPTH","SITE_MAX_DEPTH", "Qualitycontrol")

#remove extraneous columns
ad<-ad[,DATA_COLS]


##Change column names to make code easier to code
colnames(ad)[colnames(ad)=="Taxoncode"]<-"SPCODE" #Change column name
colnames(ad)[colnames(ad)=="RECENTDEAD"]<-"RDEXTENT1" #Change column name
colnames(ad)[colnames(ad)=="RECENT_GENERAL_CAUSE_CODE"]<-"GENRD1" #Change column name
colnames(ad)[colnames(ad)=="RECENT_SPECIFIC_CAUSE_CODE"]<-"RD1" #Change column name
colnames(ad)[colnames(ad)=="RECENTDEAD_2"]<-"RDEXTENT2" #Change column name
colnames(ad)[colnames(ad)=="RECENT_GENERAL_CAUSE_CODE_2"]<-"GENRD2" #Change column name
colnames(ad)[colnames(ad)=="RECENT_SPECIFIC_CAUSE_CODE_2"]<-"RD2" #Change column name
colnames(ad)[colnames(ad)=="RECENT_GENERAL_CAUSE_CODE_3"]<-"GENRD3" #Change column name
colnames(ad)[colnames(ad)=="RECENT_SPECIFIC_CAUSE_CODE_3"]<-"RD3" #Change column name
colnames(ad)[colnames(ad)=="Qualitycontrol"] <- "QC"

sort(colnames(ad))


#Change NAs in the Taxon and genus code to AAAA
ad$GENUS_CODE<-as.character(ad$GENUS_CODE)
ad$SPCODE<-as.character(ad$SPCODE)

ad <- ad %>% 
  mutate(GENUS_CODE = replace(GENUS_CODE, GENUS_CODE == "-", "AAAA"))  %>%
  mutate(SPCODE = replace(SPCODE, SPCODE == "-", "AAAA"))
View(ad)


##Calcuating segment and transect area and add column for transect area
ad<-Transectarea(ad)

write.csv(ad, "Leg_2_adult_data.csv")


#BH: create a site table
detach(package:plyr)
sv<-ad %>%
  select (ISLAND, OBS_YEAR, SITE, LATITUDE, LONGITUDE, REEF_ZONE, DEPTH_BIN, DATE_, HABITAT_CODE, SITE_MIN_DEPTH, SITE_MAX_DEPTH) %>%
  distinct(SITE, .keep_all= TRUE)
View(sv)

site_by_island <- sv %>%
  group_by(ISLAND) %>%
  summarize (n_distinct(SITE))
View(site_by_island)

#Check that you only have transect 1


# QC Checks ---------------------------------------------------------------
#Set up output csv file that reports the status of the qc checks
output<-data.frame(
QC_check<-character(),
Status<-character(),stringsAsFactors = FALSE)

output<-data.frame(
  QC_check,
  Status,stringsAsFactors = FALSE)

#QC checks on transect 1 data only
ad <- ad %>% filter (TRANSECT==1)
j <- j %>% filter (TRANSECT==1)




#2. Check number of sites is correct. Protip: sites that don't have demographic data (i.e.PQ only) will be absent from this data set but present in the site list generated from the Mission Ap
write.csv(site_by_island, "Site_check_leg2.csv")

#compare this file to the tracking spreadsheet

output[2,]<-c("Number of sites is correct","pending")




#4. Make sure that all sites have all segments. If segments are missing double check datasheets and keep a record of segments that weren't surveyed
test2<-ddply(ad,.(SITE,SEGMENT,DIVER),summarize,temp=length(SEGMENT))
eval <- acast(test2, SITE~SEGMENT, length)
#use this file to evaluate where segments may be missing
write.csv(eval, "Missing_seg_eval.csv")

# if there are multiple segment entries for a given this needs to be fixed
seg_totals<-ddply(test2,.(SITE,SEGMENT),summarize,count=length(SEGMENT))
seg_totals[seg_totals$count>1,] 

output[4,]<-c("All sites have all segments & no duplicate segments","error; HAW-04239")


# #5. Check that depths are not null and Add a new column to sitevisit table and flags any sites that don't match depth ranges for a given depth bin
# sv$db_ok<-NULL
# for (i in c(1:nrow(sv))){ #opening brace
#   if(sv$DEPTH_BIN[i] =="Deep"& sv$SITE_MIN_DEPTH[i]>=60){ #c&p
#     sv$db_ok[i] = "ok" #c&p
#   } #c&p
#   if(sv$DEPTH_BIN[i] =="Mid"& sv$SITE_MIN_DEPTH[i]>20&sv$SITE_MAX_DEPTH[i]<60){ #c&p
#     sv$db_ok[i] = "ok" #c&p
#   } #c&p
#   if(sv$DEPTH_BIN[i] =="Shallow"& sv$SITE_MAX_DEPTH[i]<=20){ #c&p
#     sv$db_ok[i] = "ok" #c&p
#   } #c&p
# } #closing curly brace for entire forloop
# sv$db_ok[is.na(sv$db_ok)]<-"error"
# subset(sv,db_ok=="error") #identify the sites that have incorrect depth bins
# 
# output[5,]<-c("Depth Bins Match site Depths","OK")


#6.Check for incorrect species-V:\PHOTOMOSAIC (1)\HARAMP\HARAMP_2019_codes.csv
ddply(ad,.(GENUS_CODE,SPCODE),summarize,temp=length(SPCODE))
ddply(j,.(GENUS_CODE,SPCODE),summarize,temp=length(SPCODE))

output[6,]<-c("Species codes are correct","OK -- although several species present that aren't scored to species, only genus")


#7.That the columns have the appropripate type of data (e.g. numeric vs. text) & no errant codes (e.g. ble instead of BLE)
#BH: changed to unique...which shows the current values in the subset plus all possible levels
sapply(ad,unique)
sapply(j, unique)

output[7,]<-c("No errant codes","ADULTS: Depreciated morph codes present (i.e. EF, LM, BP); DAMA present in GENRD1; tre present in CONDITION_2")


#8. Identify colonies <5cm in the adult database but not fragments 
ad$COLONYLENGTH[ad$COLONYLENGTH=="-"]<-NA 
ad$COLONYLENGTH <-  as.numeric(as.character(ad$COLONYLENGTH))
sm_colonies <- ad %>% filter(COLONYLENGTH < 5 & Fragment.yn != "-1" & SPCODE != "PBER")
View(sm_colonies)

output[8,]<-c("No adult colonies less than 5cm that aren't fragments","OK")



#10.Identify colonies with 0% recent dead, but PRED or DZGEN as general cause code- This check should result in 0 records
ad[ad$RDEXTENT1=="0"& ad$GENRD1!="-",]
ad[ad$RDEXTENT1=="0"& ad$RD1!="-",]
ad[ad$RDEXTENT2=="0"& ad$GENRD2!="-",]
ad[ad$RDEXTENT2=="0"& ad$RD2!="-",]
ad[ad$RDEXTENT3=="0"& ad$GENRD3!="-",]
ad[ad$RDEXTENT3=="0"& ad$RD3!="-",]
ad[ad$EXTENT_1=="0"& ad$CONDITION_1!="-",]
ad[ad$EXTENT_2=="0"& ad$CONDITION_2!="-",]
ad[ad$EXTENT_3=="0"& ad$CONDITION_3!="-",]

output[10,]<-c("Recent Dead cause is present, but %RD = 0","OK")

#11.Identify colonies with 0% recent dead, but PRED or DZGEN as general cause code- This check should result in 0 records
ad[ad$GENRD1!="-"& ad$RDEXTENT1=="-",]
ad[ad$GENRD2!="-"& ad$RDEXTENT2=="-",]
ad[ad$GENRD3!="-"& ad$RDEXTENT3=="-",]

output[11,]<-c("% Recent dead included if a cause was recorded","OK")

#12. Identify colonies with NO % recent dead. Double check that these shouldn't be 0
ad[ad$RDEXTENT1=="-" & ad$SPCODE!="AAAA",]
ad[ad$RDEXTENT2=="-" & ad$SPCODE!="AAAA",]
ad[ad$RDEXTENT3=="-" & ad$SPCODE!="AAAA",]

#Write files with the needed fixes.
RD_extent2 <- ad[ad$RDEXTENT2=="-" & ad$SPCODE!="AAAA",]
write.csv(RD_extent2, "RD2_fix.csv")output[12,]<-c("No missing %RD values","Fixes needed to RD2")

#13. Identify colonies with NO % EXTENT, but a condition. Double check that these shouldn't be 0
ad[ad$EXTENT=="-"& ad$CONDITION_1!="-",]
ad[ad$EXTENT_2=="-"& ad$CONDITION_2!="-",]
ad[ad$EXTENT_3=="-"& ad$CONDITION_3!="-",]

output[13,]<-c("All colonies with a condition have extent","Fixes needed to EXTENT1")

extent <- ad[ad$EXTENT=="-"& ad$CONDITION_1!="-",]
write.csv(extent, "Extente_fix.csv")

#14. Identify colonies witch nothing in condition column, but a value in extent
ad[ad$CONDITION_1=="-"& ad$EXTENT!="-",]
ad[ad$CONDITION_2=="-"& ad$EXTNET_2!="-",]
ad[ad$CONDITION_3=="-"& ad$EXTENT_3!="-",]

output[14,]<-c("Identify colonies with nothing in condition column, but a value in extent","OK")

#15. Identify colonies with nothing in condition column, but a value in severity. Double check that these shouldn't be 0
ad[ad$CONDITION_1=="-"& ad$SEVERITY!="-",]
ad[ad$CONDITION_2=="-"& ad$SEVERITY_2!="-",]
ad[ad$CONDITION_3=="-"& ad$SEVERITY_3!="-",]

output[15,]<-c("Identify colonies with nothing in condition column, but a value in severity","OK")

#16. Identify colonies with NO % SEVERITY, but a condition. Double check that these shouldn't be 0
ad[ad$SEVERITY=="-"& ad$CONDITION_1 %in% c("BLE","BLP"),]
ad[ad$SEVERITY2=="-"& ad$CONDITION_2%in% c("BLE","BLP"),]
ad[ad$SEVERITY3=="-"& ad$CONDITION_3%in% c("BLE","BLP"),]

#If these should be 1-5 then ask Michael to change them- it's faster than doing it manually
output[16,]<-c("BLE cause is present, but severity is null","OK")

#17. RD + OD is not greater than 100%
ad$OLDDEAD<-as.numeric(ad$OLDDEAD)
ad$RDEXTENT2<-as.numeric(ad$RDEXTENT2)
ad$RDEXTENT1<-as.numeric(ad$RDEXTENT1)
ad$totaldead<=ad$RDEXENT1+ad$RDEXTENT2+ad$OLDDEAD
ad[ad$totaldead>100]

output[17,]<-c("RD + OD <=100%","OK")


#Export QC output table with appropriate file name
write.csv(output,"HARAMP2019_Leg2QC_output.csv")



